// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfzzprfweihulxdutzvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmenpwcmZ3ZWlodWx4ZHV0enZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTY0ODksImV4cCI6MjA1OTg5MjQ4OX0.JOW6cX2gl9Gaffnf53hQAvycJJwMIF-uTWfabfScXbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);